

#define TOTAL_PLAYERS 4

#define BOX2D_CLICK_DRAW 0

#define WIDTH 1024
#define HEIGHT 768

#define KINECT_WIDTH 640
#define KINECT_HEIGHT 480


#define POWER_CHANGE_PERCENT_SHOW 1 //millis
#define POWER_CHANGE_LIFE_TIME 10000 //millis